### ISSUE TITLE
text autocorrect

### ISSUE THREAD

**Issue by tiket18** [blizzard4591/openMittsu#24] opened 2017-09-25 17:26 UTC
Today I typed the text 119 * 88 * 99 = 1036728. And it transmitted 11988 * 99.

**Comment by blizzard4591** [comment] 2017-10-04 19:06
Will be fixed in the next major release.
The bigger problem here is: This is also broken in the official Threema Client (tested on Android).

I will change my Regular Expressions to not match if the modified (in this example the star: *) is not immediately followed by a non-space character. You should contact Threema and make them aware of this problem. I might also raise this issue with them in the future.

**Comment by rugk** [comment] 2017-10-04 19:32
> This is also broken in the official Threema Client (tested on Android).

Could reproduce it.

In the web client it looks more or less, okay, does not it:
![grafik](https://user-images.githubusercontent.com/11966684/31195634-42364fbe-a94b-11e7-9cd9-a73f6f9c78d8.png)
As for the web client: @dbrgn – Is that okay or needs an issue?

As for upstream app client: @blizzard4591 did you report that issue already? If not I can do this… (beta tester)

**Comment by blizzard4591** [comment] 2017-11-18 11:09
Sorry for taking so long - no, I have not contacted them about this issue, but it should be fixed in openMittsu with the recent updates.

**Comment by tiket18** [comment] 2017-11-26 20:57
The question is closed, corrected, thank you.

**Comment by rugk** [comment] 2017-11-26 22:46
Indeed, it seems to be fixed. So, @tiket18, you can click on the close button here.

**Closed** 2017-11-27 13:53 UTC
